# Generated by Django 5.2.13 on 2026-04-14 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, message="Минимальная длина тектса вопроса - 5 символов"
                            )
                        ],
                        verbose_name="Текст вопроса",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Порядковый номер не может быть отрицательным"
                            )
                        ],
                        verbose_name="Порядок",
                    ),
                ),
                ("timer_seconds", models.PositiveIntegerField(blank=True, null=True, verbose_name="Таймер (сек)")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500, verbose_name="Текст ответа")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Правильный")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="app.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Викторина",
                "verbose_name_plural": "Викторины",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="app.quiz",
                verbose_name="Викторина",
            ),
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_code",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Код должен содержать 6 символов: заглавные буквы и цифры.",
                                regex="^[A-Z0-9]{6}$",
                            )
                        ],
                        verbose_name="Код сессии",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Время начала")),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="Время завершения")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="app.quiz",
                        verbose_name="Викторина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия викторины",
                "verbose_name_plural": "Сессии викторины",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Подключился")),
                ("total_score", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Баллы")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="app.quizsession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
                "ordering": ["-total_score", "joined_at"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Правильно")),
                ("answered_at", models.DateTimeField(auto_now_add=True, verbose_name="Время ответа")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.answeroption", verbose_name="Ответ"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="app.participant",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.question", verbose_name="Вопрос"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ участника",
                "verbose_name_plural": "Ответы участников",
                "unique_together": {("participant", "question")},
            },
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(fields=("session", "name"), name="unique_participant_name_in_session"),
        ),
    ]
